package ort.edu.ar.thp2024c1.fin;

public enum ResultadoPrestamo {
	PRESTAMO_EXITOSO,
	JUEGO_INEXISTENTE,
	RECEPTOR_INEXISTENTE,
	PRESTADOR_INEXISTENTE,
	AMIGO_INEXISTENTE,
	JUEGO_NO_DISPONIBLE,
	DEVOLUCION_OK,
	NO_EXISTE_PRESTAMO,
	AMIGO_ELIMINADO,
	USUARIO_INEXISTENTE,
	DEBE_DEVOLVER_JUEGO;
}